version: '3.4'

services: 
  reservator:
    image: ${DOCKER_REGISTRY-}reservator
    build:
      context: .
      dockerfile: App/Dockerfile
    environment:
      - DB_HOST
      - DB_DATABASE
      - DB_USER
      - DB_PW
      - BOT_TOKEN
      - DEV
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql-server-reservator-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "${DB_PW}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
volumes:
  mssql-server-reservator-data: {}