// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservator.Models;

namespace Reservator.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20210926153833_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Reservator.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ReactionsAlliesMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ReactionsAxisMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ReactionsOtherMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ReservationMessageId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Reservator.Models.GuildRoles", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Permission")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("GuildId", "RoleId", "Permission");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("Reservator.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<ulong>("User")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ReservationId");

                    b.HasIndex("GameId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Reservator.Models.Reservation", b =>
                {
                    b.HasOne("Reservator.Models.Game", "Game")
                        .WithMany("Reservations")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Reservator.Models.Game", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
